### ISSUE TITLE
Error during build: Creation method of abstract class cannot be public.

### ISSUE THREAD

**Issue by anoduck** [fusilero/libbalistica#12]
Dearly want to run this program for some time now, but receive the same build error every time I attempt to build it.  

`../test/AbstractTestCase.vala:11.2-11.24: error: Creation method of abstract class cannot be public.
	public AbstractTestCase(string name)`  

Meson output during configuration showing dependency version and information:

```
The Meson build system 
Version: 0.54.1 
Source dir: /home/User/Sandbox/libbalistica 
Build dir: /home/User/Sandbox/libbalistica/build 
Build type: native build 
Project name: libbalistica 
Project version: 1.1 
C compiler for the host machine: cc (gcc 9.3.0 "cc (Debian 9.3.0-11) 9.3.0") 
C linker for the host machine: cc ld.bfd 2.34 
Vala compiler for the host machine: valac (valac 0.48.5) 
Host machine cpu family: x86_64 
Host machine cpu: x86_64 
Dependency glib-2.0 found: YES 2.64.2 (cached) 
Dependency gobject-2.0 found: YES 2.64.2 (cached) 
Dependency gee-0.8 found: YES 0.20.3 (cached) 
Build targets in project: 2

Found ninja-1.10.0 at /usr/bin/ninja
```

It appears that all dependencies meet the required versions. Is there a more recent release of VALA that fixes this error?

**Comment by steveno** [comment]
It's not vala it's an error in the code. I thought I fixed it with ed80746 but maybe not. I'll double check.
